
package com.approuter.schemas._2008._1.lognotif;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogAndNotifManager", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", wsdlLocation = "/META-INF/wsdl/lognotif.wsdl")
public class LogAndNotifManager_Service
    extends Service
{

    private final static URL LOGANDNOTIFMANAGER_WSDL_LOCATION;
    private final static WebServiceException LOGANDNOTIFMANAGER_EXCEPTION;
    private final static QName LOGANDNOTIFMANAGER_QNAME = new QName("http://www.approuter.com/schemas/2008/1/lognotif", "LogAndNotifManager");

    static {
        LOGANDNOTIFMANAGER_WSDL_LOCATION = com.approuter.schemas._2008._1.lognotif.LogAndNotifManager_Service.class.getResource("/META-INF/wsdl/lognotif.wsdl");
        WebServiceException e = null;
        if (LOGANDNOTIFMANAGER_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/lognotif.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        LOGANDNOTIFMANAGER_EXCEPTION = e;
    }

    public LogAndNotifManager_Service() {
        super(__getWsdlLocation(), LOGANDNOTIFMANAGER_QNAME);
    }

    public LogAndNotifManager_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGANDNOTIFMANAGER_QNAME, features);
    }

    public LogAndNotifManager_Service(URL wsdlLocation) {
        super(wsdlLocation, LOGANDNOTIFMANAGER_QNAME);
    }

    public LogAndNotifManager_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGANDNOTIFMANAGER_QNAME, features);
    }

    public LogAndNotifManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogAndNotifManager_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogAndNotifManager
     */
    @WebEndpoint(name = "LogAndNotifManagerPort")
    public LogAndNotifManager getLogAndNotifManagerPort() {
        return super.getPort(new QName("http://www.approuter.com/schemas/2008/1/lognotif", "LogAndNotifManagerPort"), LogAndNotifManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogAndNotifManager
     */
    @WebEndpoint(name = "LogAndNotifManagerPort")
    public LogAndNotifManager getLogAndNotifManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.approuter.com/schemas/2008/1/lognotif", "LogAndNotifManagerPort"), LogAndNotifManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGANDNOTIFMANAGER_EXCEPTION!= null) {
            throw LOGANDNOTIFMANAGER_EXCEPTION;
        }
        return LOGANDNOTIFMANAGER_WSDL_LOCATION;
    }

}
