
package com.approuter.schemas._2008._1.lognotif;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogAndNotifManager", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.approuter.schemas._2008._1.lognotif.ObjectFactory.class,
    com.approuter.schemas._2008._1.lognotif.types.ObjectFactory.class
})
public interface LogAndNotifManager {


    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.GetLogLevelResponse
     */
    @WebMethod
    @WebResult(name = "getLogLevelResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public GetLogLevelResponse getLogLevel(
        @WebParam(name = "getLogLevel", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        GetLogLevel parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.SetLogLevelResponse
     */
    @WebMethod
    @WebResult(name = "setLogLevelResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public SetLogLevelResponse setLogLevel(
        @WebParam(name = "setLogLevel", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        SetLogLevel parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.GetLogCountResponse
     */
    @WebMethod
    @WebResult(name = "getLogCountResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public GetLogCountResponse getLogCount(
        @WebParam(name = "getLogCount", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        GetLogCount parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.SearchLogsResponse
     */
    @WebMethod
    @WebResult(name = "searchLogsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public SearchLogsResponse searchLogs(
        @WebParam(name = "searchLogs", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        SearchLogs parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.GetNotificationPolicyResponse
     */
    @WebMethod
    @WebResult(name = "getNotificationPolicyResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public GetNotificationPolicyResponse getNotificationPolicy(
        @WebParam(name = "getNotificationPolicy", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        GetNotificationPolicy parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.GetNotificationPoliciesResponse
     */
    @WebMethod
    @WebResult(name = "getNotificationPoliciesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public GetNotificationPoliciesResponse getNotificationPolicies(
        @WebParam(name = "getNotificationPolicies", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        GetNotificationPolicies parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.CreateNotificationPolicyResponse
     */
    @WebMethod
    @WebResult(name = "createNotificationPolicyResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public CreateNotificationPolicyResponse createNotificationPolicy(
        @WebParam(name = "createNotificationPolicy", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        CreateNotificationPolicy parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.DeleteNotificationPolicyResponse
     */
    @WebMethod
    @WebResult(name = "deleteNotificationPolicyResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public DeleteNotificationPolicyResponse deleteNotificationPolicy(
        @WebParam(name = "deleteNotificationPolicy", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        DeleteNotificationPolicy parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.GetEmailEndpointResponse
     */
    @WebMethod
    @WebResult(name = "getEmailEndpointResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public GetEmailEndpointResponse getEmailEndpoint(
        @WebParam(name = "getEmailEndpoint", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        GetEmailEndpoint parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.SetEmailEndpointResponse
     */
    @WebMethod
    @WebResult(name = "setEmailEndpointResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public SetEmailEndpointResponse setEmailEndpoint(
        @WebParam(name = "setEmailEndpoint", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        SetEmailEndpoint parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.GetSnmpEndpointResponse
     */
    @WebMethod
    @WebResult(name = "getSnmpEndpointResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public GetSnmpEndpointResponse getSnmpEndpoint(
        @WebParam(name = "getSnmpEndpoint", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        GetSnmpEndpoint parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.lognotif.SetSnmpEndpointResponse
     */
    @WebMethod
    @WebResult(name = "setSnmpEndpointResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "result")
    public SetSnmpEndpointResponse setSnmpEndpoint(
        @WebParam(name = "setSnmpEndpoint", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", partName = "parameters")
        SetSnmpEndpoint parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/lognotif", header = true, partName = "sessionId")
        String sessionId);

}
