
package com.approuter.schemas._2008._1.system;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SystemManager", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", wsdlLocation = "/META-INF/wsdl/system.wsdl")
public class SystemManager_Service
    extends Service
{

    private final static URL SYSTEMMANAGER_WSDL_LOCATION;
    private final static WebServiceException SYSTEMMANAGER_EXCEPTION;
    private final static QName SYSTEMMANAGER_QNAME = new QName("http://www.approuter.com/schemas/2008/1/system", "SystemManager");

    static {
        SYSTEMMANAGER_WSDL_LOCATION = com.approuter.schemas._2008._1.system.SystemManager_Service.class.getResource("/META-INF/wsdl/system.wsdl");
        WebServiceException e = null;
        if (SYSTEMMANAGER_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/system.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SYSTEMMANAGER_EXCEPTION = e;
    }

    public SystemManager_Service() {
        super(__getWsdlLocation(), SYSTEMMANAGER_QNAME);
    }

    public SystemManager_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SYSTEMMANAGER_QNAME, features);
    }

    public SystemManager_Service(URL wsdlLocation) {
        super(wsdlLocation, SYSTEMMANAGER_QNAME);
    }

    public SystemManager_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SYSTEMMANAGER_QNAME, features);
    }

    public SystemManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SystemManager_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SystemManager
     */
    @WebEndpoint(name = "SystemManagerPort")
    public SystemManager getSystemManagerPort() {
        return super.getPort(new QName("http://www.approuter.com/schemas/2008/1/system", "SystemManagerPort"), SystemManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SystemManager
     */
    @WebEndpoint(name = "SystemManagerPort")
    public SystemManager getSystemManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.approuter.com/schemas/2008/1/system", "SystemManagerPort"), SystemManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SYSTEMMANAGER_EXCEPTION!= null) {
            throw SYSTEMMANAGER_EXCEPTION;
        }
        return SYSTEMMANAGER_WSDL_LOCATION;
    }

}
