
package com.approuter.schemas._2008._1.system;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SystemManager", targetNamespace = "http://www.approuter.com/schemas/2008/1/system")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.approuter.schemas._2008._1.system.ObjectFactory.class,
    com.approuter.schemas._2008._1.util.types.ObjectFactory.class,
    com.approuter.schemas.router._1000.netconfig02.ObjectFactory.class
})
public interface SystemManager {


    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.system.GetApplianceNameResponse
     */
    @WebMethod
    @WebResult(name = "getApplianceNameResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "result")
    public GetApplianceNameResponse getApplianceName(
        @WebParam(name = "getApplianceName", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "parameters")
        GetApplianceName parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.system.SetApplianceNameResponse
     */
    @WebMethod
    @WebResult(name = "setApplianceNameResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "result")
    public SetApplianceNameResponse setApplianceName(
        @WebParam(name = "setApplianceName", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "parameters")
        SetApplianceName parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.system.GetSystemInfoResponse
     */
    @WebMethod
    @WebResult(name = "getSystemInfoResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "result")
    public GetSystemInfoResponse getSystemInfo(
        @WebParam(name = "getSystemInfo", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "parameters")
        GetSystemInfo parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.system.ExecuteCommandResponse
     */
    @WebMethod
    @WebResult(name = "executeCommandResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "result")
    public ExecuteCommandResponse executeCommand(
        @WebParam(name = "executeCommand", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "parameters")
        ExecuteCommand parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.system.DownloadPostmortemResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "downloadPostmortemResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "result")
    public DownloadPostmortemResponse downloadPostmortem(
        @WebParam(name = "downloadPostmortem", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "parameters")
        DownloadPostmortem parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.system.GetNetworkConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "getNetworkConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "result")
    public GetNetworkConfigurationResponse getNetworkConfiguration(
        @WebParam(name = "getNetworkConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "parameters")
        GetNetworkConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.system.SetNetworkConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "setNetworkConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "result")
    public SetNetworkConfigurationResponse setNetworkConfiguration(
        @WebParam(name = "setNetworkConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", partName = "parameters")
        SetNetworkConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/system", header = true, partName = "sessionId")
        String sessionId);

}
