
package com.approuter.schemas._2008._1.deployment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeploymentManager", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.approuter.schemas._2008._1.deployment.ObjectFactory.class,
    com.approuter.schema.router._1000.security._03.ObjectFactory.class,
    com.approuter.schemas._2008._1.deployment.types.ObjectFactory.class,
    com.approuter.schemas._2008._1.util.types.ObjectFactory.class
})
public interface DeploymentManager {


    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.ExportRepositoryResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "exportRepositoryResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public ExportRepositoryResponse exportRepository(
        @WebParam(name = "exportRepository", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        ExportRepository parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.ImportRepositoryResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "importRepositoryResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public ImportRepositoryResponse importRepository(
        @WebParam(name = "importRepository", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        ImportRepository parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.DownloadProjectResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "downloadProjectResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public DownloadProjectResponse downloadProject(
        @WebParam(name = "downloadProject", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        DownloadProject parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.StartResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "startResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public StartResponse start(
        @WebParam(name = "start", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        Start parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.StopAndCancelResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "stopAndCancelResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public StopAndCancelResponse stopAndCancel(
        @WebParam(name = "stopAndCancel", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        StopAndCancel parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.StopAndWaitResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "stopAndWaitResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public StopAndWaitResponse stopAndWait(
        @WebParam(name = "stopAndWait", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        StopAndWait parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.SuspendResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "suspendResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public SuspendResponse suspend(
        @WebParam(name = "suspend", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        Suspend parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.ResumeResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "resumeResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public ResumeResponse resume(
        @WebParam(name = "resume", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        Resume parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.UndeployResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "undeployResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public UndeployResponse undeploy(
        @WebParam(name = "undeploy", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        Undeploy parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.CancelJobResponse
     */
    @WebMethod
    @WebResult(name = "cancelJobResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public CancelJobResponse cancelJob(
        @WebParam(name = "cancelJob", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        CancelJob parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetProjectResponse
     */
    @WebMethod
    @WebResult(name = "getProjectResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetProjectResponse getProject(
        @WebParam(name = "getProject", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetProject parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "getConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetConfigurationResponse getConfiguration(
        @WebParam(name = "getConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.CreateUserConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "createUserConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public CreateUserConfigurationResponse createUserConfiguration(
        @WebParam(name = "createUserConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        CreateUserConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetUserConfigurationsResponse
     */
    @WebMethod
    @WebResult(name = "getUserConfigurationsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetUserConfigurationsResponse getUserConfigurations(
        @WebParam(name = "getUserConfigurations", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetUserConfigurations parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetUserConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "getUserConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetUserConfigurationResponse getUserConfiguration(
        @WebParam(name = "getUserConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetUserConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.DeleteUserConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "deleteUserConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public DeleteUserConfigurationResponse deleteUserConfiguration(
        @WebParam(name = "deleteUserConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        DeleteUserConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetAssetPropertiesResponse
     */
    @WebMethod
    @WebResult(name = "getAssetPropertiesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetAssetPropertiesResponse getAssetProperties(
        @WebParam(name = "getAssetProperties", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetAssetProperties parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetAssetScriptResponse
     */
    @WebMethod
    @WebResult(name = "getAssetScriptResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetAssetScriptResponse getAssetScript(
        @WebParam(name = "getAssetScript", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetAssetScript parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.ExecuteAssetScriptResponse
     */
    @WebMethod
    @WebResult(name = "executeAssetScriptResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public ExecuteAssetScriptResponse executeAssetScript(
        @WebParam(name = "executeAssetScript", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        ExecuteAssetScript parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.PublishProjectResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "publishProjectResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public PublishProjectResponse publishProject(
        @WebParam(name = "publishProject", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        PublishProject parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.CloneConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "cloneConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public CloneConfigurationResponse cloneConfiguration(
        @WebParam(name = "cloneConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        CloneConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.CreateConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "createConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public CreateConfigurationResponse createConfiguration(
        @WebParam(name = "createConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        CreateConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.SavePropertiesResponse
     */
    @WebMethod
    @WebResult(name = "savePropertiesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public SavePropertiesResponse saveProperties(
        @WebParam(name = "saveProperties", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        SaveProperties parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.SaveOrchestrationValuesResponse
     */
    @WebMethod
    @WebResult(name = "saveOrchestrationValuesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public SaveOrchestrationValuesResponse saveOrchestrationValues(
        @WebParam(name = "saveOrchestrationValues", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        SaveOrchestrationValues parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetRuleResponse
     */
    @WebMethod
    @WebResult(name = "getRuleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetRuleResponse getRule(
        @WebParam(name = "getRule", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetRule parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetRulesResponse
     */
    @WebMethod
    @WebResult(name = "getRulesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetRulesResponse getRules(
        @WebParam(name = "getRules", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetRules parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.CreateRuleResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "createRuleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public CreateRuleResponse createRule(
        @WebParam(name = "createRule", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        CreateRule parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.CreateRepeatingRuleResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "createRepeatingRuleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public CreateRepeatingRuleResponse createRepeatingRule(
        @WebParam(name = "createRepeatingRule", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        CreateRepeatingRule parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.DeleteRuleResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "deleteRuleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public DeleteRuleResponse deleteRule(
        @WebParam(name = "deleteRule", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        DeleteRule parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetConfigurationGroupsResponse
     */
    @WebMethod
    @WebResult(name = "getConfigurationGroupsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetConfigurationGroupsResponse getConfigurationGroups(
        @WebParam(name = "getConfigurationGroups", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetConfigurationGroups parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.SetConfigurationGroupsResponse
     */
    @WebMethod
    @WebResult(name = "setConfigurationGroupsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public SetConfigurationGroupsResponse setConfigurationGroups(
        @WebParam(name = "setConfigurationGroups", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        SetConfigurationGroups parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.GetAllProjectsResponse
     */
    @WebMethod
    @WebResult(name = "getAllProjectsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public GetAllProjectsResponse getAllProjects(
        @WebParam(name = "getAllProjects", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        GetAllProjects parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.DeleteProjectResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "deleteProjectResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public DeleteProjectResponse deleteProject(
        @WebParam(name = "deleteProject", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        DeleteProject parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.deployment.DeleteConfigurationResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "deleteConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "result")
    public DeleteConfigurationResponse deleteConfiguration(
        @WebParam(name = "deleteConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", partName = "parameters")
        DeleteConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", header = true, partName = "sessionId")
        String sessionId)
        throws Exception_Exception
    ;

}
