
package com.approuter.schemas._2008._1.deployment;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeploymentManager", targetNamespace = "http://www.approuter.com/schemas/2008/1/deployment", wsdlLocation = "/META-INF/wsdl/deployment.wsdl")
public class DeploymentManager_Service
    extends Service
{

    private final static URL DEPLOYMENTMANAGER_WSDL_LOCATION;
    private final static WebServiceException DEPLOYMENTMANAGER_EXCEPTION;
    private final static QName DEPLOYMENTMANAGER_QNAME = new QName("http://www.approuter.com/schemas/2008/1/deployment", "DeploymentManager");

    static {
        DEPLOYMENTMANAGER_WSDL_LOCATION = com.approuter.schemas._2008._1.deployment.DeploymentManager_Service.class.getResource("/META-INF/wsdl/deployment.wsdl");
        WebServiceException e = null;
        if (DEPLOYMENTMANAGER_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/deployment.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        DEPLOYMENTMANAGER_EXCEPTION = e;
    }

    public DeploymentManager_Service() {
        super(__getWsdlLocation(), DEPLOYMENTMANAGER_QNAME);
    }

    public DeploymentManager_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPLOYMENTMANAGER_QNAME, features);
    }

    public DeploymentManager_Service(URL wsdlLocation) {
        super(wsdlLocation, DEPLOYMENTMANAGER_QNAME);
    }

    public DeploymentManager_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPLOYMENTMANAGER_QNAME, features);
    }

    public DeploymentManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeploymentManager_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeploymentManager
     */
    @WebEndpoint(name = "DeploymentManagerPort")
    public DeploymentManager getDeploymentManagerPort() {
        return super.getPort(new QName("http://www.approuter.com/schemas/2008/1/deployment", "DeploymentManagerPort"), DeploymentManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeploymentManager
     */
    @WebEndpoint(name = "DeploymentManagerPort")
    public DeploymentManager getDeploymentManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.approuter.com/schemas/2008/1/deployment", "DeploymentManagerPort"), DeploymentManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPLOYMENTMANAGER_EXCEPTION!= null) {
            throw DEPLOYMENTMANAGER_EXCEPTION;
        }
        return DEPLOYMENTMANAGER_WSDL_LOCATION;
    }

}
