
package com.approuter.schemas._2008._1.security;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecurityManager", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", wsdlLocation = "/META-INF/wsdl/security.wsdl")
public class SecurityManager_Service
    extends Service
{

    private final static URL SECURITYMANAGER_WSDL_LOCATION;
    private final static WebServiceException SECURITYMANAGER_EXCEPTION;
    private final static QName SECURITYMANAGER_QNAME = new QName("http://www.approuter.com/schemas/2008/1/security", "SecurityManager");

    static {
        SECURITYMANAGER_WSDL_LOCATION = com.approuter.schemas._2008._1.security.SecurityManager_Service.class.getResource("/META-INF/wsdl/security.wsdl");
        WebServiceException e = null;
        if (SECURITYMANAGER_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/META-INF/wsdl/security.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SECURITYMANAGER_EXCEPTION = e;
    }

    public SecurityManager_Service() {
        super(__getWsdlLocation(), SECURITYMANAGER_QNAME);
    }

    public SecurityManager_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECURITYMANAGER_QNAME, features);
    }

    public SecurityManager_Service(URL wsdlLocation) {
        super(wsdlLocation, SECURITYMANAGER_QNAME);
    }

    public SecurityManager_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECURITYMANAGER_QNAME, features);
    }

    public SecurityManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityManager_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecurityManager
     */
    @WebEndpoint(name = "SecurityManagerPort")
    public SecurityManager getSecurityManagerPort() {
        return super.getPort(new QName("http://www.approuter.com/schemas/2008/1/security", "SecurityManagerPort"), SecurityManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecurityManager
     */
    @WebEndpoint(name = "SecurityManagerPort")
    public SecurityManager getSecurityManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.approuter.com/schemas/2008/1/security", "SecurityManagerPort"), SecurityManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECURITYMANAGER_EXCEPTION!= null) {
            throw SECURITYMANAGER_EXCEPTION;
        }
        return SECURITYMANAGER_WSDL_LOCATION;
    }

}
