
package com.approuter.schemas._2008._1.security;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-2b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecurityManager", targetNamespace = "http://www.approuter.com/schemas/2008/1/security")
@XmlSeeAlso({
    com.approuter.schema.router._1000.security._03.ObjectFactory.class,
    com.approuter.schemas._2008._1.security.ObjectFactory.class
})
public interface SecurityManager {


    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", className = "com.approuter.schemas._2008._1.security.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", className = "com.approuter.schemas._2008._1.security.LoginResponse")
    public String login(
        @WebParam(name = "username", targetNamespace = "http://www.approuter.com/schemas/2008/1/security")
        String username,
        @WebParam(name = "password", targetNamespace = "http://www.approuter.com/schemas/2008/1/security")
        String password);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.LogoutResponse
     */
    @WebMethod
    @WebResult(name = "logoutResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public LogoutResponse logout(
        @WebParam(name = "logout", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        Logout parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.CurrentScopeResponse
     */
    @WebMethod
    @WebResult(name = "currentScopeResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public CurrentScopeResponse currentScope(
        @WebParam(name = "currentScope", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        CurrentScope parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.SetCurrentScopeResponse
     */
    @WebMethod
    @WebResult(name = "setCurrentScopeResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SetCurrentScopeResponse setCurrentScope(
        @WebParam(name = "setCurrentScope", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        SetCurrentScope parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.SetCurrentScopeByIdResponse
     */
    @WebMethod
    @WebResult(name = "setCurrentScopeByIdResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SetCurrentScopeByIdResponse setCurrentScopeById(
        @WebParam(name = "setCurrentScopeById", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        SetCurrentScopeById parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetScopeResponse
     */
    @WebMethod
    @WebResult(name = "getScopeResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetScopeResponse getScope(
        @WebParam(name = "getScope", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetScope parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetScopeByIdResponse
     */
    @WebMethod
    @WebResult(name = "getScopeByIdResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetScopeByIdResponse getScopeById(
        @WebParam(name = "getScopeById", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetScopeById parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetScopesByParentIdResponse
     */
    @WebMethod
    @WebResult(name = "getScopesByParentIdResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetScopesByParentIdResponse getScopesByParentId(
        @WebParam(name = "getScopesByParentId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetScopesByParentId parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.CreateUserResponse
     */
    @WebMethod
    @WebResult(name = "createUserResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public CreateUserResponse createUser(
        @WebParam(name = "createUser", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        CreateUser parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.DeleteUserResponse
     */
    @WebMethod
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteUserResponse deleteUser(
        @WebParam(name = "deleteUser", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        DeleteUser parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.UpdateUserResponse
     */
    @WebMethod
    @WebResult(name = "updateUserResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateUserResponse updateUser(
        @WebParam(name = "updateUser", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        UpdateUser parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.EnableUserResponse
     */
    @WebMethod
    @WebResult(name = "enableUserResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public EnableUserResponse enableUser(
        @WebParam(name = "enableUser", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        EnableUser parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.DisableUserResponse
     */
    @WebMethod
    @WebResult(name = "disableUserResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DisableUserResponse disableUser(
        @WebParam(name = "disableUser", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        DisableUser parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.IsUserEnabledResponse
     */
    @WebMethod
    @WebResult(name = "isUserEnabledResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public IsUserEnabledResponse isUserEnabled(
        @WebParam(name = "isUserEnabled", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        IsUserEnabled parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.ChangePasswordResponse
     */
    @WebMethod
    @WebResult(name = "changePasswordResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ChangePasswordResponse changePassword(
        @WebParam(name = "changePassword", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        ChangePassword parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.UserExistsResponse
     */
    @WebMethod
    @WebResult(name = "userExistsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UserExistsResponse userExists(
        @WebParam(name = "userExists", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        UserExists parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetUserResponse
     */
    @WebMethod
    @WebResult(name = "getUserResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetUserResponse getUser(
        @WebParam(name = "getUser", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetUser parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetUserByIdResponse
     */
    @WebMethod
    @WebResult(name = "getUserByIdResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetUserByIdResponse getUserById(
        @WebParam(name = "getUserById", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetUserById parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetRoleResponse
     */
    @WebMethod
    @WebResult(name = "getRoleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetRoleResponse getRole(
        @WebParam(name = "getRole", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetRole parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetRoleByIdResponse
     */
    @WebMethod
    @WebResult(name = "getRoleByIdResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetRoleByIdResponse getRoleById(
        @WebParam(name = "getRoleById", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetRoleById parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.CreateRoleResponse
     */
    @WebMethod
    @WebResult(name = "createRoleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public CreateRoleResponse createRole(
        @WebParam(name = "createRole", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        CreateRole parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GrantRoleResponse
     */
    @WebMethod
    @WebResult(name = "grantRoleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GrantRoleResponse grantRole(
        @WebParam(name = "grantRole", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GrantRole parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.RevokeRoleResponse
     */
    @WebMethod
    @WebResult(name = "revokeRoleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RevokeRoleResponse revokeRole(
        @WebParam(name = "revokeRole", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        RevokeRole parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.DeleteRoleResponse
     */
    @WebMethod
    @WebResult(name = "deleteRoleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public DeleteRoleResponse deleteRole(
        @WebParam(name = "deleteRole", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        DeleteRole parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.UpdateRoleResponse
     */
    @WebMethod
    @WebResult(name = "updateRoleResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public UpdateRoleResponse updateRole(
        @WebParam(name = "updateRole", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        UpdateRole parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.RoleExistsResponse
     */
    @WebMethod
    @WebResult(name = "roleExistsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RoleExistsResponse roleExists(
        @WebParam(name = "roleExists", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        RoleExists parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.AddRoleToRoleGroupResponse
     */
    @WebMethod
    @WebResult(name = "addRoleToRoleGroupResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public AddRoleToRoleGroupResponse addRoleToRoleGroup(
        @WebParam(name = "addRoleToRoleGroup", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        AddRoleToRoleGroup parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.RemoveRoleFromRoleGroupResponse
     */
    @WebMethod
    @WebResult(name = "removeRoleFromRoleGroupResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RemoveRoleFromRoleGroupResponse removeRoleFromRoleGroup(
        @WebParam(name = "removeRoleFromRoleGroup", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        RemoveRoleFromRoleGroup parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.ListUsersResponse
     */
    @WebMethod
    @WebResult(name = "listUsersResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ListUsersResponse listUsers(
        @WebParam(name = "listUsers", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        ListUsers parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.FilterUsersResponse
     */
    @WebMethod
    @WebResult(name = "filterUsersResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public FilterUsersResponse filterUsers(
        @WebParam(name = "filterUsers", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        FilterUsers parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.FilterNewUsersResponse
     */
    @WebMethod
    @WebResult(name = "filterNewUsersResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public FilterNewUsersResponse filterNewUsers(
        @WebParam(name = "filterNewUsers", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        FilterNewUsers parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetUsersResponse
     */
    @WebMethod
    @WebResult(name = "getUsersResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetUsersResponse getUsers(
        @WebParam(name = "getUsers", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetUsers parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.ListRolesResponse
     */
    @WebMethod
    @WebResult(name = "listRolesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ListRolesResponse listRoles(
        @WebParam(name = "listRoles", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        ListRoles parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetRolesResponse
     */
    @WebMethod
    @WebResult(name = "getRolesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetRolesResponse getRoles(
        @WebParam(name = "getRoles", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetRoles parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.ListGrantableRolesResponse
     */
    @WebMethod
    @WebResult(name = "listGrantableRolesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ListGrantableRolesResponse listGrantableRoles(
        @WebParam(name = "listGrantableRoles", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        ListGrantableRoles parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetGrantedRolesResponse
     */
    @WebMethod
    @WebResult(name = "getGrantedRolesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetGrantedRolesResponse getGrantedRoles(
        @WebParam(name = "getGrantedRoles", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetGrantedRoles parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetImpliedRolesResponse
     */
    @WebMethod
    @WebResult(name = "getImpliedRolesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetImpliedRolesResponse getImpliedRoles(
        @WebParam(name = "getImpliedRoles", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetImpliedRoles parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetRoleGroupsResponse
     */
    @WebMethod
    @WebResult(name = "getRoleGroupsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetRoleGroupsResponse getRoleGroups(
        @WebParam(name = "getRoleGroups", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetRoleGroups parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetRoleUsersResponse
     */
    @WebMethod
    @WebResult(name = "getRoleUsersResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetRoleUsersResponse getRoleUsers(
        @WebParam(name = "getRoleUsers", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetRoleUsers parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetRolesInRoleGroupResponse
     */
    @WebMethod
    @WebResult(name = "getRolesInRoleGroupResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetRolesInRoleGroupResponse getRolesInRoleGroup(
        @WebParam(name = "getRolesInRoleGroup", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetRolesInRoleGroup parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.IsRealmUserResponse
     */
    @WebMethod
    @WebResult(name = "isRealmUserResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public IsRealmUserResponse isRealmUser(
        @WebParam(name = "isRealmUser", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        IsRealmUser parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.HasPrivilegeResponse
     */
    @WebMethod
    @WebResult(name = "hasPrivilegeResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public HasPrivilegeResponse hasPrivilege(
        @WebParam(name = "hasPrivilege", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        HasPrivilege parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.ListPrivilegesResponse
     */
    @WebMethod
    @WebResult(name = "listPrivilegesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ListPrivilegesResponse listPrivileges(
        @WebParam(name = "listPrivileges", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        ListPrivileges parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GrantPrivilegeResponse
     */
    @WebMethod
    @WebResult(name = "grantPrivilegeResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GrantPrivilegeResponse grantPrivilege(
        @WebParam(name = "grantPrivilege", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GrantPrivilege parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GrantPrivilegesResponse
     */
    @WebMethod
    @WebResult(name = "grantPrivilegesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GrantPrivilegesResponse grantPrivileges(
        @WebParam(name = "grantPrivileges", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GrantPrivileges parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.RevokePrivilegeResponse
     */
    @WebMethod
    @WebResult(name = "revokePrivilegeResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RevokePrivilegeResponse revokePrivilege(
        @WebParam(name = "revokePrivilege", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        RevokePrivilege parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.RevokePrivilegesResponse
     */
    @WebMethod
    @WebResult(name = "revokePrivilegesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RevokePrivilegesResponse revokePrivileges(
        @WebParam(name = "revokePrivileges", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        RevokePrivileges parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.ListAvailableActionsResponse
     */
    @WebMethod
    @WebResult(name = "listAvailableActionsResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ListAvailableActionsResponse listAvailableActions(
        @WebParam(name = "listAvailableActions", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        ListAvailableActions parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.ClearPrivilegesResponse
     */
    @WebMethod
    @WebResult(name = "clearPrivilegesResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public ClearPrivilegesResponse clearPrivileges(
        @WebParam(name = "clearPrivileges", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        ClearPrivileges parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetLdapConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "getLdapConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetLdapConfigurationResponse getLdapConfiguration(
        @WebParam(name = "getLdapConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetLdapConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.SetLdapConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "setLdapConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SetLdapConfigurationResponse setLdapConfiguration(
        @WebParam(name = "setLdapConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        SetLdapConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetKerberosServerNameResponse
     */
    @WebMethod
    @WebResult(name = "getKerberosServerNameResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetKerberosServerNameResponse getKerberosServerName(
        @WebParam(name = "getKerberosServerName", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetKerberosServerName parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.GetKerberosRealmResponse
     */
    @WebMethod
    @WebResult(name = "getKerberosRealmResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetKerberosRealmResponse getKerberosRealm(
        @WebParam(name = "getKerberosRealm", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        GetKerberosRealm parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.SetKerberosConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "setKerberosConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public SetKerberosConfigurationResponse setKerberosConfiguration(
        @WebParam(name = "setKerberosConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        SetKerberosConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

    /**
     * 
     * @param sessionId
     * @param parameters
     * @return
     *     returns com.approuter.schemas._2008._1.security.RemoveKerberosConfigurationResponse
     */
    @WebMethod
    @WebResult(name = "removeKerberosConfigurationResponse", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RemoveKerberosConfigurationResponse removeKerberosConfiguration(
        @WebParam(name = "removeKerberosConfiguration", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", partName = "parameters")
        RemoveKerberosConfiguration parameters,
        @WebParam(name = "sessionId", targetNamespace = "http://www.approuter.com/schemas/2008/1/security", header = true, partName = "sessionId")
        String sessionId);

}
